### ISSUE TITLE
ถามเรื่องการใช้งาน Service ข้างนอก

### ISSUE THREAD

**Issue by kanathips** [up1/soa_group2#19]
ผมสามารถใช้ Service ของ Auth0 ได้ไหม ? 
เพราะมันจะทำให้ Member Service ของกลุ่มผมไม่มีความจำเป็นที่ต้องเขียน End point signin signup เอง + กับปลอดภัยของระบบที่เพิ่มขึ้น

@up1

**Comment by up1** [comment]
ทำเองเลยครับ
