### ISSUE TITLE
สอบถามเรื่องคะแนน service monitoring

### ISSUE THREAD

**Issue by leconize** [up1/soa_group2#22]
จากหน้า https://docs.google.com/spreadsheets/d/14jP1DOwUcvGQWRTxUEnMVia9jPWEpNdNwyKlJdxR0zY/edit#gid=1601742361

อยากสอบถามว่าคะแนนช่องmonitoring มาจาก gafana Prometheus ใช่ไหมครับ

**Comment by leconize** [comment]
@up1

**Comment by up1** [comment]
ใช่ครับ
